### ISSUE TITLE
udev_sigfox_edk.a

### ISSUE THREAD

**Issue by danielfsilva88** [udev-br/SIGFOX-EDK#1]
At the manual, in section 7.1.4, it was said that is necessary to add a static library, "udev_sigfox_edk.a" (in respective picture written as "libudev_sigfox_edk.a"), in template project, but there isn't any file as that in all github project folder despite several references about it in readme.md files.

Could you guys post that file or explain any alternative to it?

Thanks!

**Comment by Lucasbadur** [comment]
Hi Daniel!

As stated in our [readme](https://github.com/udev-br/SIGFOX-EDK#getting-started), we are still in the process of making our library available to the general public.
For now, we're asking for people to contact us at [contato@udev.com.br](mailto:contato@udev.com.br) so we can analyze each case and send the library to those interested.
Please send me a message at lucas.badur@udev.com.br and I'll get you sorted as soon as I can!

Regards,
Lucas
